# link below for readme
# https://github.com/itzg/docker-minecraft-server

services:
  ftb-server:
    container_name: ftb-server
    image: itzg/minecraft-server:java8-multiarch
    stdin_open: true
    tty: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FTBA"
      FTB_MODPACK_ID: "126"
      MEMORY: "4G"
      WHITELIST: "tbauer516"
      OPS: "tbauer516"
    restart: unless-stopped
    volumes:
      - ./server-data:/data
